# =======================================================
# Example Secrets Configuration for Shylock Online
# =======================================================
# Copy this file to:   .streamlit/secrets.toml
# Then replace the placeholder values with your real ones.
# The actual secrets.toml should NOT be committed to GitHub.
# =======================================================

# -------------------------------
# Supabase Configuration
# -------------------------------
[supabase]
url = "https://your-project.supabase.co"
anon_key = "YOUR_ANON_KEY"
service_role_key = "YOUR_SERVICE_ROLE_KEY"

# -------------------------------
# Application Settings
# -------------------------------
[app]
# MVP plan by default: "free" or "pro"
plan = "free"

# -------------------------------
# Email / SMTP (optional)
# -------------------------------
# Uncomment and configure if you want email features (Pro tier)
[email]
smtp_server = "smtp.example.com"
smtp_port = 587
username = "user@example.com"
password = "supersecretpassword"
from_address = "noreply@example.com"
